### ISSUE TITLE
Libs errors 

### ISSUE THREAD

**Issue by gaveer** [lownignitus/HeirloomQuestTracker#1]
28x Couldn't open HeirloomQuestTracker\Libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml

2x Couldn't open LibSharedMedia-3.0-6010002\LibSharedMedia-3.0.toc

**Comment by lownignitus** [comment]
So seems I accidentally deleted CallbackHandler from the Libs folder.

I have no clue why you are getting a LibSharedMedia error from HQT, it does not use that Lib. 

Could you include the entire error if there is more?

**Comment by gaveer** [comment]
i use bugger addone and thats all what i get 
http://prntscr.com/m6mkbq

**Comment by lownignitus** [comment]
Well I just pushed an update for this with needed Lib. When you can, update and check if this fixed things for you.

**Comment by gaveer** [comment]
well test it now , what about the LibSharedMedia ?

**Comment by lownignitus** [comment]
Well as I said, I do not understand why you got an error for that. That error also does not mention HQT. But HQT should not be looking for that to function, as I do not use it.

I will comb through the other Libs, I am pretty sure I have all the Lib dependencies for all the others included. but Ill double check.

**Comment by gaveer** [comment]
maybe error from other addone well test it alone .

**Comment by lownignitus** [comment]
Ok, Curse just approved the update.
